//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.11 at 05:22:23 AM CET 
//


package com.alopec.rpg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mobile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mobile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}posX"/>
 *         &lt;element ref="{}posY"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mobile", propOrder = {
    "posX",
    "posY"
})
public class Mobile {

    protected int posX;
    protected int posY;

    /**
     * Gets the value of the posX property.
     * 
     */
    public int getPosX() {
        return posX;
    }

    /**
     * Sets the value of the posX property.
     * 
     */
    public void setPosX(int value) {
        this.posX = value;
    }

    /**
     * Gets the value of the posY property.
     * 
     */
    public int getPosY() {
        return posY;
    }

    /**
     * Sets the value of the posY property.
     * 
     */
    public void setPosY(int value) {
        this.posY = value;
    }

}
