//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.11 at 05:22:23 AM CET 
//


package com.alopec.rpg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for player complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="player">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}life"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}posX"/>
 *         &lt;element ref="{}posY"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "player", propOrder = {
    "life",
    "name",
    "posX",
    "posY"
})
public class Player {

    protected int life;
    @XmlElement(required = true)
    protected String name;
    protected int posX;
    protected int posY;

    /**
     * Gets the value of the life property.
     * 
     */
    public int getLife() {
        return life;
    }

    /**
     * Sets the value of the life property.
     * 
     */
    public void setLife(int value) {
        this.life = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the posX property.
     * 
     */
    public int getPosX() {
        return posX;
    }

    /**
     * Sets the value of the posX property.
     * 
     */
    public void setPosX(int value) {
        this.posX = value;
    }

    /**
     * Gets the value of the posY property.
     * 
     */
    public int getPosY() {
        return posY;
    }

    /**
     * Sets the value of the posY property.
     * 
     */
    public void setPosY(int value) {
        this.posY = value;
    }

}
